Devs2Blu.Projeto.SistemaRH.Web/Models/ErrorViewModel.cs
namespace Devs2Blu.Projeto.SistemaRH.Web.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Devs2Blu.Projeto.SistemaRH.Web/Controllers/HomeController.cs
using Devs2Blu.Projeto.SistemaRH.Web.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Devs2Blu.Projeto.SistemaRH.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Devs2Blu.Projeto.SistemaRH.Web/Controllers/TipoUsuariosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Devs2Blu.Projeto.SistemaRH.Domain.Entities;
using Devs2Blu.Projeto.SistemaRH.Infra.Data;
using Devs2Blu.Projeto.SistemaRH.Domain.IRepositories;
using Devs2Blu.Projeto.SistemaRH.Domain.DTO;

namespace Devs2Blu.Projeto.SistemaRH.Web.Controllers
{
    [Route("/usuarios/tipos")]
    public class TipoUsuariosController : Controller
    {
        private readonly ITipoUsuariosRepository _repository;

        public TipoUsuariosController(ITipoUsuariosRepository repository)
        {
            _repository = repository;
        }

        #region RetornoDasViews

        public IActionResult Index()
        {
            var allTipoCategories = _repository
                .FindAll()
                .Select(tipoUsuario => new TipoUsuariosDTO()
                    {
                        Id= tipoUsuario.Id,
                        Nome = tipoUsuario.Nome,
                    })
                .ToList();
            return View(allTipoCategories);
        }

        //[Route("/detalhes")]
        //public IActionResult Details()
        //{
        //    return View();
        //}

        [Route("/criar")]
        public IActionResult Create() 
        {
            return View();
        }

        [Route("/editar")]
        public IActionResult Edit()
        {
            return View();
        }

        [Route("/deletar")]
        public IActionResult Delete() 
        {
            return View();
        }

        #endregion

        [HttpPost, Route("/createTipo")]
        public async Task<IActionResult> CreateTipoUsuario([Bind("Nome")]TipoUsuarios obj)
        {
            await _repository.Save(obj);
            return RedirectToAction("Index");
        }

        [HttpPut, Route("/alteraTipo")]
        public async Task<IActionResult> UpdateTipoUsuario([Bind("Id", "Nome")]TipoUsuarios obj)
        {
            await _repository.Update(obj);
            return RedirectToAction("Index");
        }

        [HttpDelete, Route("/deleteTipo")]
        public async Task<IActionResult> DeleteTipoUsuario([Bind("Id", "Nome")]TipoUsuarios obj)
        {
            await _repository.Delete(obj);
            TempData["Message"] = $"Tipo de Usuário : {obj.Nome} excluído com sucesso!";
            return RedirectToAction("Index");
        }
    }
}

Devs2Blu.Projeto.SistemaRH.Web/Views/Empresa/Create.cshtml
@model Devs2Blu.Projeto.SistemaRH.Domain.Entities.Empresa

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Empresa</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RazaoSocial" class="control-label"></label>
                <input asp-for="RazaoSocial" class="form-control" />
                <span asp-validation-for="RazaoSocial" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CNPJ" class="control-label"></label>
                <input asp-for="CNPJ" class="form-control" />
                <span asp-validation-for="CNPJ" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CEO" class="control-label"></label>
                <input asp-for="CEO" class="form-control" />
                <span asp-validation-for="CEO" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Devs2Blu.Projeto.SistemaRH.Web/Views/Empresa/Delete.cshtml
@model Devs2Blu.Projeto.SistemaRH.Domain.Entities.Empresa

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Empresa</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nome)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.RazaoSocial)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.RazaoSocial)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CNPJ)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CNPJ)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CEO)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CEO)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Devs2Blu.Projeto.SistemaRH.Web/Views/Empresa/Details.cshtml
@model Devs2Blu.Projeto.SistemaRH.Domain.Entities.Empresa

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Empresa</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nome)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.RazaoSocial)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.RazaoSocial)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CNPJ)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CNPJ)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CEO)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CEO)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Devs2Blu.Projeto.SistemaRH.Web/Views/Empresa/Edit.cshtml
@model Devs2Blu.Projeto.SistemaRH.Domain.Entities.Empresa

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Empresa</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RazaoSocial" class="control-label"></label>
                <input asp-for="RazaoSocial" class="form-control" />
                <span asp-validation-for="RazaoSocial" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CNPJ" class="control-label"></label>
                <input asp-for="CNPJ" class="form-control" />
                <span asp-validation-for="CNPJ" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CEO" class="control-label"></label>
                <input asp-for="CEO" class="form-control" />
                <span asp-validation-for="CEO" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Devs2Blu.Projeto.SistemaRH.Web/Views/Empresa/Index.cshtml
@model IEnumerable<Devs2Blu.Projeto.SistemaRH.Domain.Entities.Empresa>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.RazaoSocial)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CNPJ)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CEO)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Nome)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.RazaoSocial)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CNPJ)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CEO)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

Devs2Blu.Projeto.SistemaRH.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Devs2Blu.Projeto.SistemaRH.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Devs2Blu.Projeto.SistemaRH.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Devs2Blu.Projeto.SistemaRH.Web.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Devs2Blu.Projeto.SistemaRH.Web</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="TipoUsuarios" asp-action="Index">TipoUsuario</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Devs2Blu.Projeto.SistemaRH.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Devs2Blu.Projeto.SistemaRH.Web/Views/TipoUsuarios/Create.cshtml
@model Devs2Blu.Projeto.SistemaRH.Domain.Entities.TipoUsuarios

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>TipoUsuarios</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="CreateTipoUsuario" method="POST">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group mt-3">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Devs2Blu.Projeto.SistemaRH.Web/Views/TipoUsuarios/Delete.cshtml
@model Devs2Blu.Projeto.SistemaRH.Domain.Entities.TipoUsuarios

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>TipoUsuarios</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nome)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Devs2Blu.Projeto.SistemaRH.Web/Views/TipoUsuarios/Details.cshtml
@model Devs2Blu.Projeto.SistemaRH.Domain.Entities.TipoUsuarios

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>TipoUsuarios</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nome)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Devs2Blu.Projeto.SistemaRH.Web/Views/TipoUsuarios/Edit.cshtml
@model Devs2Blu.Projeto.SistemaRH.Domain.Entities.TipoUsuarios

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>TipoUsuarios</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Devs2Blu.Projeto.SistemaRH.Web/Views/TipoUsuarios/Index.cshtml
@model IEnumerable<Devs2Blu.Projeto.SistemaRH.Domain.DTO.TipoUsuariosDTO>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nome)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Nome)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                @*<a asp-action="Details" asp-route-id="@item.Id">Details</a> |*@
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>